apiVersion: v1
kind: Service
metadata:
  name: question-service
  annotations:
    cloud.google.com/backend-config: '{"default": "question-service-backendconfig"}'
  labels:
    app: question-service
spec:
  selector:
    app: question-service
  type: ClusterIP
  ports:
    - name: question-service
      port: 3002
      targetPort: 3002