apiVersion: v1
kind: Service
metadata:
  name: chat-service
  annotations:
    cloud.google.com/backend-config: '{"default": "chat-service-backendconfig"}'
  labels:
    app: chat-service
spec:
  selector:
    app: chat-service
  type: ClusterIP
  ports:
    - name: chat-service
      port: 3006
      targetPort: 3006