services:
  nginx:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "80:80"

  user:
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
      args:
        - PORT=${PORT_USER}
    ports:
      - ${PORT_USER}:${PORT_USER}
    networks:
      - backend
    environment:
      - ENV
      - DB_CLOUD_URI=${DB_URI_USER}
      - DB_LOCAL_URI=${DB_URI_USER}
      - JWT_SECRET

  questions:
    container_name: question-service
    build:
      context: ./question-service
      dockerfile: Dockerfile
      args:
        - PORT=${PORT_QUESTION}
    ports:
      - ${PORT_QUESTION}:${PORT_QUESTION}
    networks:
      - backend
    environment:
      - ENV
      - DB_CLOUD_URI=${DB_URI_QUESTION}

  matching-redis:
    image: redis
    networks:
      - matching
    expose:
      - 6379

  matching:
    container_name: matching-service
    build:
      context: ./matching-service
      dockerfile: Dockerfile
      args:
        - PORT=${PORT_MATCHING}
    ports:
      - ${PORT_MATCHING}:${PORT_MATCHING}
    depends_on:
      - matching-redis
    networks:
      - matching
      - backend
    environment:
      - REDIS_URL=redis://matching-redis:6379

networks:
  matching:
    driver: bridge
  backend:
    driver: bridge
