services:
  user:
    build:
      context: ./user-service
      dockerfile: Dockerfile
      args:
        - PORT=${PORT_USER}
    ports:
      - ${PORT_USER}:${PORT_USER}
    environment:
      - ENV
      - DB_CLOUD_URI
      - DB_LOCAL_URI
      - JWT_SECRET

  questions:
    build:
      context: ./question-service
      dockerfile: Dockerfile
      args:
        - PORT=${PORT_QUESTION}
    ports:
      - ${PORT_QUESTION}:${PORT_QUESTION}
    environment:
      - ENV
      - DB_CLOUD_URI
      - DB_LOCAL_URI
