apiVersion: v1
kind: Service
metadata:
  name: matching-service
  labels:
    app: matching-service
spec:
  selector:
    app: matching-service
  type: ClusterIP
  ports:
    - name: match-service
      port: 3003
      targetPort: 3003