apiVersion: v1
kind: Service
metadata:
  name: matching-service
  annotations:
    cloud.google.com/backend-config: '{"default": "matching-service-backendconfig"}'
  labels:
    app: matching-service
spec:
  selector:
    app: matching-service
  type: ClusterIP
  ports:
    - name: matching-service
      port: 3003
      targetPort: 3003