apiVersion: v1
kind: Service
metadata:
  name: collab-service
  annotations:
    cloud.google.com/backend-config: '{"ports": {"3004":"collab-service-backendconfig"}}'
  labels:
    app: collab-service
spec:
  selector:
    app: collab-service
  type: ClusterIP
  ports:
    - name: collab-service
      port: 3004
      targetPort: 3004

      